name: CI-macOS

on:
  pull_request:
    branches: [ main ] # change back to master if your repo uses master

jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.2"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build and Test
        run: xcodebuild clean build test \
          -project EssentialFeed/EssentialFeed.xcodeproj \
          -scheme "CI_macOS" \
          -sdk macosx \
          -destination "platform=macOS" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          ONLY_ACTIVE_ARCH=YES \
          -derivedDataPath DerivedData

